# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goflux < Formula
  desc "🚀 The fastest way to build full-stack applications with Go + TypeScript"
  homepage "https://github.com/barisgit/goflux"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/barisgit/goflux/releases/download/v0.1.8/flux_0.1.8_darwin_amd64.tar.gz"
      sha256 "ab95b6c6248e9285032511f63492d7a9a47812384213ed75941a16333949dbab"

      def install
        bin.install "flux"
      end
    end
    on_arm do
      url "https://github.com/barisgit/goflux/releases/download/v0.1.8/flux_0.1.8_darwin_arm64.tar.gz"
      sha256 "da3762a35842358ef0ac8eb5ad369b1029c537637576de07a8a9e5971544b559"

      def install
        bin.install "flux"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/barisgit/goflux/releases/download/v0.1.8/flux_0.1.8_linux_amd64.tar.gz"
        sha256 "48c7b12c83559768eda33873924313ac4c866a971a0b283702d9d6a215b4ca5b"

        def install
          bin.install "flux"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/barisgit/goflux/releases/download/v0.1.8/flux_0.1.8_linux_arm64.tar.gz"
        sha256 "a22d333ab5d691f0d1982593624750ec63930f83356cfba3edbde625a7507911"

        def install
          bin.install "flux"
        end
      end
    end
  end

  test do
    system "#{bin}/flux", "--version"
  end
end
