# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flux < Formula
  desc "🚀 The fastest way to build full-stack applications with Go + TypeScript"
  homepage "https://github.com/barisgit/goflux"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/barisgit/goflux/releases/download/v0.1.7/flux_0.1.7_darwin_amd64.tar.gz"
      sha256 "fe0215f06a264e7ad89b382878214e61dd926d9b4be0d9a0429a0246f3f292ca"

      def install
        bin.install "flux"
      end
    end
    on_arm do
      url "https://github.com/barisgit/goflux/releases/download/v0.1.7/flux_0.1.7_darwin_arm64.tar.gz"
      sha256 "f862cfc6bec826a0ce6acec5a26637ed283084b5113496d0f2a279bd4a1667f0"

      def install
        bin.install "flux"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/barisgit/goflux/releases/download/v0.1.7/flux_0.1.7_linux_amd64.tar.gz"
        sha256 "5183def88ae5e573bcfc8a8317f8c534343417b200c2da0d2abf5082d1e56159"

        def install
          bin.install "flux"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/barisgit/goflux/releases/download/v0.1.7/flux_0.1.7_linux_arm64.tar.gz"
        sha256 "bbc85b3ea49693dcaa6461a39a4bcca06fdb23eb71501302f24e003ec73f9028"

        def install
          bin.install "flux"
        end
      end
    end
  end

  test do
    system "#{bin}/flux", "--version"
  end
end
